# Generated by Django 3.0.3 on 2020-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
