# Generated by Django 3.0.3 on 2020-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0002_auto_20200321_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='phone number'),
        ),
    ]
