# Generated by Django 3.0.3 on 2020-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0003_auto_20200321_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
