# Generated by Django 3.0.3 on 2020-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0004_auto_20200321_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='comment count'),
        ),
    ]
