# Generated by Django 3.0.3 on 2020-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0005_auto_20200322_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
