# Generated by Django 3.0.3 on 2020-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukobook', '0007_auto_20200322_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liker',
            field=models.IntegerField(default=0),
        ),
    ]
